/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login_ (void);
GtkWidget* create_space_admin_ (void);
GtkWidget* create_space_members_ (void);
GtkWidget* create_space_coachs_ (void);
GtkWidget* create_gestion_des_membres_ (void);
