/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login_ (void)
{
  GtkWidget *login_;
  GtkWidget *eventbox1;
  GtkWidget *fixed1;
  GtkWidget *user;
  GtkWidget *password;
  GtkWidget *label4;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *btconnexion;

  login_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login_), _("window1"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (login_), eventbox1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed1);

  user = gtk_entry_new ();
  gtk_widget_show (user);
  gtk_fixed_put (GTK_FIXED (fixed1), user, 344, 248);
  gtk_widget_set_size_request (user, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (user), 8226);

  password = gtk_entry_new ();
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 352, 392);
  gtk_widget_set_size_request (password, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (password), 8226);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 768, 592);
  gtk_widget_set_size_request (label4, 96, 24);

  label2 = gtk_label_new (_("Password : "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 176, 344);
  gtk_widget_set_size_request (label2, 200, 128);

  label3 = gtk_label_new (_("Log in "));
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 312, 144);
  gtk_widget_set_size_request (label3, 275, 68);
  gtk_misc_set_alignment (GTK_MISC (label3), 0.47, 0.45);
  gtk_label_set_width_chars (GTK_LABEL (label3), 4);
  gtk_label_set_angle (GTK_LABEL (label3), 3);

  label1 = gtk_label_new (_("user name :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 184, 232);
  gtk_widget_set_size_request (label1, 185, 72);

  btconnexion = gtk_button_new_with_mnemonic (_("connexion "));
  gtk_widget_show (btconnexion);
  gtk_fixed_put (GTK_FIXED (fixed1), btconnexion, 400, 488);
  gtk_widget_set_size_request (btconnexion, 120, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login_, login_, "login_");
  GLADE_HOOKUP_OBJECT (login_, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (login_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login_, user, "user");
  GLADE_HOOKUP_OBJECT (login_, password, "password");
  GLADE_HOOKUP_OBJECT (login_, label4, "label4");
  GLADE_HOOKUP_OBJECT (login_, label2, "label2");
  GLADE_HOOKUP_OBJECT (login_, label3, "label3");
  GLADE_HOOKUP_OBJECT (login_, label1, "label1");
  GLADE_HOOKUP_OBJECT (login_, btconnexion, "btconnexion");

  return login_;
}

GtkWidget*
create_space_admin_ (void)
{
  GtkWidget *space_admin_;
  GtkWidget *fixed2;
  GtkWidget *space_admin_;
  GtkWidget *manage_coachs_;
  GtkWidget *manage_memebrs_;
  GtkWidget *center_administrations_;
  GtkWidget *Organise_Sports_Courses;
  GtkWidget *events_planification;

  space_admin_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (space_admin_), _("window2"));
  gtk_window_set_modal (GTK_WINDOW (space_admin_), TRUE);
  gtk_window_set_gravity (GTK_WINDOW (space_admin_), GDK_GRAVITY_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (space_admin_), fixed2);

  space_admin_ = gtk_label_new (_("space admin "));
  gtk_widget_show (space_admin_);
  gtk_fixed_put (GTK_FIXED (fixed2), space_admin_, 312, 88);
  gtk_widget_set_size_request (space_admin_, 256, 80);

  manage_coachs_ = gtk_button_new_with_mnemonic (_("manage coachs "));
  gtk_widget_show (manage_coachs_);
  gtk_fixed_put (GTK_FIXED (fixed2), manage_coachs_, 216, 312);
  gtk_widget_set_size_request (manage_coachs_, 200, 48);

  manage_memebrs_ = gtk_button_new_with_mnemonic (_("manage memebrs "));
  gtk_widget_show (manage_memebrs_);
  gtk_fixed_put (GTK_FIXED (fixed2), manage_memebrs_, 216, 232);
  gtk_widget_set_size_request (manage_memebrs_, 200, 48);

  center_administrations_ = gtk_button_new_with_mnemonic (_("center administrations "));
  gtk_widget_show (center_administrations_);
  gtk_fixed_put (GTK_FIXED (fixed2), center_administrations_, 216, 400);
  gtk_widget_set_size_request (center_administrations_, 192, 48);

  Organise_Sports_Courses = gtk_button_new_with_mnemonic (_("Organise Sports Courses"));
  gtk_widget_show (Organise_Sports_Courses);
  gtk_fixed_put (GTK_FIXED (fixed2), Organise_Sports_Courses, 216, 472);
  gtk_widget_set_size_request (Organise_Sports_Courses, 200, 40);

  events_planification = gtk_button_new_with_mnemonic (_("events planification"));
  gtk_widget_show (events_planification);
  gtk_fixed_put (GTK_FIXED (fixed2), events_planification, 216, 552);
  gtk_widget_set_size_request (events_planification, 216, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (space_admin_, space_admin_, "space_admin_");
  GLADE_HOOKUP_OBJECT (space_admin_, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (space_admin_, space_admin_, "space_admin_");
  GLADE_HOOKUP_OBJECT (space_admin_, manage_coachs_, "manage_coachs_");
  GLADE_HOOKUP_OBJECT (space_admin_, manage_memebrs_, "manage_memebrs_");
  GLADE_HOOKUP_OBJECT (space_admin_, center_administrations_, "center_administrations_");
  GLADE_HOOKUP_OBJECT (space_admin_, Organise_Sports_Courses, "Organise_Sports_Courses");
  GLADE_HOOKUP_OBJECT (space_admin_, events_planification, "events_planification");

  return space_admin_;
}

GtkWidget*
create_space_members_ (void)
{
  GtkWidget *space_members_;
  GtkWidget *fixed3;
  GtkWidget *label13;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;

  space_members_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (space_members_), _("window3"));
  gtk_window_set_default_size (GTK_WINDOW (space_members_), 800, 700);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (space_members_), fixed3);

  label13 = gtk_label_new (_("Space Members "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 424, 112);
  gtk_widget_set_size_request (label13, 240, 64);

  button3 = gtk_button_new_with_mnemonic (_("Log in "));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 464, 216);
  gtk_widget_set_size_request (button3, 176, 48);

  button4 = gtk_button_new_with_mnemonic (_("particiapte "));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 464, 304);
  gtk_widget_set_size_request (button4, 176, 48);

  button5 = gtk_button_new_with_mnemonic (_("resere private caoch "));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 464, 392);
  gtk_widget_set_size_request (button5, 176, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (space_members_, space_members_, "space_members_");
  GLADE_HOOKUP_OBJECT (space_members_, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (space_members_, label13, "label13");
  GLADE_HOOKUP_OBJECT (space_members_, button3, "button3");
  GLADE_HOOKUP_OBJECT (space_members_, button4, "button4");
  GLADE_HOOKUP_OBJECT (space_members_, button5, "button5");

  return space_members_;
}

GtkWidget*
create_space_coachs_ (void)
{
  GtkWidget *space_coachs_;
  GtkWidget *fixed4;
  GtkWidget *inscription_;
  GtkWidget *join_course_;
  GtkWidget *equipements_reservation_;
  GtkWidget *coches_;

  space_coachs_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (space_coachs_), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (space_coachs_), fixed4);
  gtk_container_set_border_width (GTK_CONTAINER (fixed4), 6);

  inscription_ = gtk_button_new_with_mnemonic (_("centre inscription "));
  gtk_widget_show (inscription_);
  gtk_fixed_put (GTK_FIXED (fixed4), inscription_, 232, 144);
  gtk_widget_set_size_request (inscription_, 176, 32);

  join_course_ = gtk_button_new_with_mnemonic (_("join course "));
  gtk_widget_show (join_course_);
  gtk_fixed_put (GTK_FIXED (fixed4), join_course_, 232, 208);
  gtk_widget_set_size_request (join_course_, 176, 48);

  equipements_reservation_ = gtk_button_new_with_mnemonic (_("equipements reservation "));
  gtk_widget_show (equipements_reservation_);
  gtk_fixed_put (GTK_FIXED (fixed4), equipements_reservation_, 232, 296);
  gtk_widget_set_size_request (equipements_reservation_, 184, 40);

  coches_ = gtk_label_new (_("space coach "));
  gtk_widget_show (coches_);
  gtk_fixed_put (GTK_FIXED (fixed4), coches_, 200, 56);
  gtk_widget_set_size_request (coches_, 256, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (space_coachs_, space_coachs_, "space_coachs_");
  GLADE_HOOKUP_OBJECT (space_coachs_, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (space_coachs_, inscription_, "inscription_");
  GLADE_HOOKUP_OBJECT (space_coachs_, join_course_, "join_course_");
  GLADE_HOOKUP_OBJECT (space_coachs_, equipements_reservation_, "equipements_reservation_");
  GLADE_HOOKUP_OBJECT (space_coachs_, coches_, "coches_");

  return space_coachs_;
}

GtkWidget*
create_gestion_des_membres_ (void)
{
  GtkWidget *gestion_des_membres_;
  GtkWidget *fixed7;
  GtkWidget *entry1;
  GtkWidget *treeview1;
  GtkWidget *MANAGE_MEMBERS;
  GtkWidget *LABEL_CHERCHER_;
  GtkWidget *comboboxentry1;
  GtkWidget *chercher_;
  GtkWidget *trier_par_;
  GtkWidget *action_sur_les_membres_;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *ID_;
  GtkWidget *NAME;
  GtkWidget *label20;
  GtkWidget *AGE_;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *SEXE;

  gestion_des_membres_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_des_membres_, 700, 600);
  gtk_window_set_title (GTK_WINDOW (gestion_des_membres_), _("window1"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (gestion_des_membres_), fixed7);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1, 240, 112);
  gtk_widget_set_size_request (entry1, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 48, 208);
  gtk_widget_set_size_request (treeview1, 624, 160);

  MANAGE_MEMBERS = gtk_label_new (_("MANAGE MEMBERS"));
  gtk_widget_show (MANAGE_MEMBERS);
  gtk_fixed_put (GTK_FIXED (fixed7), MANAGE_MEMBERS, 208, 24);
  gtk_widget_set_size_request (MANAGE_MEMBERS, 300, 30);
  gtk_misc_set_alignment (GTK_MISC (MANAGE_MEMBERS), 0.44, 0.5);

  LABEL_CHERCHER_ = gtk_label_new (_("search for a member "));
  gtk_widget_show (LABEL_CHERCHER_);
  gtk_fixed_put (GTK_FIXED (fixed7), LABEL_CHERCHER_, 8, 104);
  gtk_widget_set_size_request (LABEL_CHERCHER_, 248, 48);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry1, 584, 176);
  gtk_widget_set_size_request (comboboxentry1, 93, 24);

  chercher_ = gtk_button_new_with_mnemonic (_("search"));
  gtk_widget_show (chercher_);
  gtk_fixed_put (GTK_FIXED (fixed7), chercher_, 504, 112);
  gtk_widget_set_size_request (chercher_, 80, 32);

  trier_par_ = gtk_label_new (_("sort by"));
  gtk_widget_show (trier_par_);
  gtk_fixed_put (GTK_FIXED (fixed7), trier_par_, 504, 176);
  gtk_widget_set_size_request (trier_par_, 72, 24);

  action_sur_les_membres_ = gtk_label_new (_("ACTION ON MEMRBES "));
  gtk_widget_show (action_sur_les_membres_);
  gtk_fixed_put (GTK_FIXED (fixed7), action_sur_les_membres_, 8, 376);
  gtk_widget_set_size_request (action_sur_les_membres_, 208, 32);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2, 112, 440);
  gtk_widget_set_size_request (entry2, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3, 112, 488);
  gtk_widget_set_size_request (entry3, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4, 112, 536);
  gtk_widget_set_size_request (entry4, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  ID_ = gtk_label_new (_("ID"));
  gtk_widget_show (ID_);
  gtk_fixed_put (GTK_FIXED (fixed7), ID_, 32, 432);
  gtk_widget_set_size_request (ID_, 72, 32);

  NAME = gtk_label_new (_("NAME"));
  gtk_widget_show (NAME);
  gtk_fixed_put (GTK_FIXED (fixed7), NAME, 32, 480);
  gtk_widget_set_size_request (NAME, 72, 32);

  label20 = gtk_label_new (_("first name"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed7), label20, 32, 536);
  gtk_widget_set_size_request (label20, 72, 32);

  AGE_ = gtk_label_new (_("AGE"));
  gtk_widget_show (AGE_);
  gtk_fixed_put (GTK_FIXED (fixed7), AGE_, 296, 432);
  gtk_widget_set_size_request (AGE_, 72, 32);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 112, 440);
  gtk_widget_set_size_request (entry5, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed7), entry6, 112, 440);
  gtk_widget_set_size_request (entry6, 120, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed7), entry7, 360, 432);
  gtk_widget_set_size_request (entry7, 88, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  button7 = gtk_button_new_with_mnemonic (_("button7"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed7), button7, 568, 432);
  gtk_widget_set_size_request (button7, 112, 32);

  button8 = gtk_button_new_with_mnemonic (_("button8"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 568, 488);
  gtk_widget_set_size_request (button8, 112, 32);

  button9 = gtk_button_new_with_mnemonic (_("button9"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed7), button9, 568, 544);
  gtk_widget_set_size_request (button9, 112, 32);

  SEXE = gtk_label_new (_("SEXE"));
  gtk_widget_show (SEXE);
  gtk_fixed_put (GTK_FIXED (fixed7), SEXE, 304, 488);
  gtk_widget_set_size_request (SEXE, 49, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_membres_, gestion_des_membres_, "gestion_des_membres_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, MANAGE_MEMBERS, "MANAGE_MEMBERS");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, LABEL_CHERCHER_, "LABEL_CHERCHER_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, chercher_, "chercher_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, trier_par_, "trier_par_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, action_sur_les_membres_, "action_sur_les_membres_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, ID_, "ID_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, NAME, "NAME");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, AGE_, "AGE_");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, button9, "button9");
  GLADE_HOOKUP_OBJECT (gestion_des_membres_, SEXE, "SEXE");

  return gestion_des_membres_;
}

