/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *login_;
  GtkWidget *space_admin_;
  GtkWidget *space_members_;
  GtkWidget *space_coachs_;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  login_ = create_login_ ();
  gtk_widget_show (login_);
  space_admin_ = create_space_admin_ ();
  gtk_widget_show (space_admin_);
  space_members_ = create_space_members_ ();
  gtk_widget_show (space_members_);
  space_coachs_ = create_space_coachs_ ();
  gtk_widget_show (space_coachs_);

  gtk_main ();
  return 0;
}

